// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD85_OYLI_wwd1mqNfTUJgu7SLmk8svi7g',
    appId: '1:743029425556:web:0c663ea9eb8f5b30593b81',
    messagingSenderId: '743029425556',
    projectId: 'netlnk',
    authDomain: 'netlnk.firebaseapp.com',
    storageBucket: 'netlnk.appspot.com',
    measurementId: 'G-D07EGHRL4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqGMxFwuKQw8OEU5h5IJNkkmtOomG_Lbg',
    appId: '1:743029425556:android:d98174643ba8b5dc593b81',
    messagingSenderId: '743029425556',
    projectId: 'netlnk',
    storageBucket: 'netlnk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfnPv0KGjB5QTcJPlLTBImKpsBE7lNDqk',
    appId: '1:743029425556:ios:186a364ad1a0d9c7593b81',
    messagingSenderId: '743029425556',
    projectId: 'netlnk',
    storageBucket: 'netlnk.appspot.com',
    iosBundleId: 'com.example.netlnk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfnPv0KGjB5QTcJPlLTBImKpsBE7lNDqk',
    appId: '1:743029425556:ios:186a364ad1a0d9c7593b81',
    messagingSenderId: '743029425556',
    projectId: 'netlnk',
    storageBucket: 'netlnk.appspot.com',
    iosBundleId: 'com.example.netlnk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD85_OYLI_wwd1mqNfTUJgu7SLmk8svi7g',
    appId: '1:743029425556:web:4fa932855bf6d403593b81',
    messagingSenderId: '743029425556',
    projectId: 'netlnk',
    authDomain: 'netlnk.firebaseapp.com',
    storageBucket: 'netlnk.appspot.com',
    measurementId: 'G-Y17M28Y8YR',
  );
}
